apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-kafka
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 768Mi
  vault:
    enabled: false
  leaderElection: true
  envFrom:
    - secret: google-sql-dinesykmeldte-backend-dinesykmeldte-backend-2b15651f
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: flex-syketilfelle
          namespace: flex
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-gcp.flex.flex-syketilfelle/.default
    - name: CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:dinesykmeldte-backend-db-instance