apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dinesykmeldte-kafka
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 768Mi
    enabled: false
  leaderElection: true
  envFrom:
    - secret: google-sql-dinesykmeldte-backend-dinesykmeldte-backend-2b15651f
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: flex-syketilfelle
          namespace: flex
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default
    - name: CLOUD_SQL_INSTANCE
      value: teamsykmelding-dev-1d34:europe-north1:dinesykmeldte-backend-db-instance